#ifndef SINTAX_ANALIZER
#define SINTAX_ANALIZER

#define KW_MODULE                258
#define KW_WHILE                 269
#define KW_EXTERN                260
#define KW_BREAK                 265
#define KW_CONTINUE              266
#define KW_IF                    267
#define KW_ELSE                  273
#define KW_FALSE                 281
#define KW_TRUE                  280
#define KW_SWITCH                270
#define KW_CASE                  274
#define KW_DEFAULT               271
#define KW_GOTO                  268
#define KW_LABEL                 264
#define KW_INT                   279
#define KW_BOOL                  275
#define KW_FLOAT                 278
#define KW_CHAR                  276
#define KW_UNTYPED               318
#define KW_VOID                  261
#define KW_RETURN                272
#define KW_START                 262
#define LPAREN                   322
#define RPAREN                   323
#define LBRACE                   324
#define RBRACE                   325
#define LBRACKET                 326
#define RBRACKET                 327
#define COMMA                    328
#define OP_ADD                   329
#define OP_SUBTRACT              330
#define OP_BITWISE_COMPLEMENT    331
#define OP_MULTIPLY              332
#define OP_DIVIDE                333
#define OP_MODULUS               334
#define OP_LESS                  335
#define OP_LESSEQUAL             292
#define OP_GREATER               337
#define OP_GREATEREQUAL          291
#define OP_EQUAL                 289
#define OP_EQUALEQUAL            367
#define OP_NOTEQUAL              290
#define OP_LOGICAL_OR            285
#define OP_NOT                   343
#define OP_BITWISE_RSHIFT        287
#define OP_BITWISE_LSHIFT        288
#define OP_BITWISE_XOR           346
#define OP_LOGICAL_AND           286
#define OP_BITWISE_AND           348
#define SEMICOLON                349
#define COLON                    351
#define ARROW                    263
#define OP_ASSIGN                353
#define OP_BITWISE_OR            354
#define OP_TERNARY_IF            355
#define KW_IMPORT                356
#define TRUE                     357
#define FALSE                    358
#define HEX                      359
#define BIN                      360
#define INT                      282
#define CHAR                     284
#define FLOAT                    283
#define STRING                   364
#define IDENTIFIER               259
#define KW_DO                    277
#define EMPTY                    570
#define ERROR                    606
#define EOI                      0

int yylex();
#endif