
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[383] =
    {   0,
        0,    0,   70,   68,   69,    3,   49,   68,   68,   41,
       54,   68,   31,   32,   39,   36,   35,   37,   40,   63,
       63,   63,   56,   55,   42,   57,   44,   59,   67,   33,
       34,   52,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   29,   58,   30,
       38,    4,   47,    0,    0,   53,    0,   65,   63,   28,
        0,    1,   64,   63,   63,    0,   62,   51,   43,   46,
       45,   50,   67,   67,   67,   67,   67,   67,   67,    5,
       67,   67,   67,   67,   67,   11,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   48,   66,    0,    0,

        0,    1,   64,   63,   63,   61,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   20,   67,
       67,   67,   67,   67,   67,   67,   67,   67,    0,    2,
       64,   63,   63,   61,   67,   21,   67,   16,   23,   67,
       67,   12,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   14,   67,   25,   67,    0,   64,   63,   63,   61,
       67,    9,   67,   67,   67,   13,   22,   67,   19,   67,
       67,   27,   67,   67,    7,    0,   64,   63,   63,   61,
       67,   67,   67,    8,   67,    6,   26,   15,   67,   60,
       64,   63,   63,   61,   67,   67,   17,   67,   24,   64,

       63,   63,   61,   67,   10,   67,   64,   63,   63,   61,
       67,   67,   64,   63,   63,   61,   67,   67,   64,   63,
       63,   67,   67,   64,   63,   63,   67,   67,   64,   63,
       63,   67,   67,   64,   63,   63,   67,   67,   64,   63,
       63,   67,   67,   64,   63,   63,   67,   67,   64,   63,
       63,   67,   67,   64,   63,   63,   67,   67,   64,   63,
       63,   67,   67,   64,   63,   63,   67,   67,   64,   63,
       63,   67,   18,   64,   63,   63,   67,   64,   63,   63,
       67,   64,   63,   63,   67,   64,   63,   63,   67,   64,
       63,   63,   67,   64,   63,   63,   67,   64,   63,   63,

       67,   64,   63,   63,   67,   64,   63,   63,   67,   64,
       63,   63,   67,   64,   63,   63,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
        0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   27,   27,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       30,    1,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   28,   43,   44,   45,   46,
       47,   48,   28,   49,   50,   51,   52,   53,   54,   55,
       56,   28,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    5,    5,    1,
        1,    1,    6,    4,    4,    4,    4,    4,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[425] =
    {   0,
        0,    0,  979,  976,  980,  975,   59,  974,   60,  973,
       61,   62,  972,  971,  970,  969,  968,   66,   63,   74,
       79,   99,  967,  966,   64,   65,   80,  965,  964,  963,
      962,  961,   75,   94,   98,   68,   72,  105,  108,   77,
      106,  111,   76,   71,  119,  123,  130,  960,  124,  959,
      958,  980,  980,  129,  914,  980,  949,  980,  124,  980,
      945,    0,  119,  139,  144,    0,  980,  980,  980,  980,
      980,  980,    0,  909,  917,  904,  919,  906,  912,    0,
      900,  898,  904,  900,  895,    0,  894,  909,  906,  891,
      907,  898,  887,  887,  895,  894,  980,  146,  887,  831,

      144,    0,  148,  157,  165,    0,    0,  788,  785,  779,
      767,  764,  779,  774,  773,  760,  775,  760,    0,  768,
      753,  737,  732,  729,  730,  694,  712,  700,  679,  706,
      160,  170,  175,    0,    0,    0,  674,    0,    0,  663,
      635,    0,  637,  643,  612,  619,  610,  598,  575,  572,
      582,    0,  552,    0,  554,  542,  178,  183,  188,    0,
        0,    0,  533,  507,  492,    0,    0,  478,    0,  474,
      453,    0,  445,  435,    0,  409,  191,  196,  201,    0,
        0,  395,  383,    0,  375,    0,    0,    0,  371,  980,
      204,  209,  214,    0,    0,  357,    0,  332,    0,  217,

      222,  227,    0,    0,    0,  327,  230,  235,  240,    0,
        0,  319,  243,  248,  253,  980,    0,  305,  256,  261,
      266,    0,  281,  269,  274,  279,    0,  279,  282,  287,
      292,    0,  267,  295,  300,  305,    0,  250,  308,  313,
      318,    0,  244,  321,  326,  331,    0,  216,  334,  339,
      344,    0,  207,  347,  352,  357,    0,  200,  360,  365,
      370,    0,  174,  373,  378,  383,    0,  169,  386,  391,
      396,    0,    0,  399,  404,  409,    0,  412,  417,  422,
        0,  425,  430,  435,    0,  438,  443,  448,    0,  451,
      456,  461,    0,  464,  469,  474,    0,  477,  482,  487,

        0,  490,  495,  500,    0,  503,  508,  513,    0,  516,
      521,  526,  980,  529,  534,  539,  542,  545,  548,  980,
      552,  555,  558,  563,  566,  570,  576,  579,  584,  587,
      590,  594,  597,  602,  608,  611,  615,  618,  621,  626,
      629,  633,  639,  642,  647,  650,  653,  657,  660,  665,
      671,  674,  678,  681,  684,  689,  692,  696,  702,  705,
      710,  713,  716,  720,  723,  728,  734,  737,  741,  744,
      747,  752,  755,  759,  765,  768,  773,  776,  779,  783,
      785,  980,  820,  825,  829,  835,  841,  196,  844,  183,
      847,  168,  850,  165,  853,  146,  856,  142,  859,  129,

      862,   68,  865,  868,  871,  874,  877,  880,  883,  886,
      889,  892,  895,  898,  901,  904,  907,  910,  913,  916,
      919,  922,  925,  928
    } ;

static const flex_int16_t yy_def[425] =
    {   0,
      382,    1,  382,  382,  382,  382,  382,  383,  382,  382,
      382,  384,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  385,  382,
      382,  382,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  382,  382,  382,
      382,  382,  382,  383,  382,  382,  382,  382,  382,  382,
      386,  387,  382,  382,  382,  388,  382,  382,  382,  382,
      382,  382,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  382,  383,  382,  386,

      386,  387,  382,  382,  382,  390,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  391,  391,
      391,  391,  391,  391,  391,  391,  391,  391,  382,  386,
      382,  382,  382,  392,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  393,  393,  393,  393,  393,
      393,  393,  393,  393,  393,  382,  382,  382,  382,  394,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  382,  382,  382,  382,  396,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  382,
      382,  382,  382,  398,  399,  399,  399,  399,  399,  382,

      382,  382,  400,  401,  401,  401,  382,  382,  382,  402,
      403,  403,  382,  382,  382,  382,  404,  404,  382,  382,
      382,  405,  405,  382,  382,  382,  406,  406,  382,  382,
      382,  407,  407,  382,  382,  382,  408,  408,  382,  382,
      382,  409,  409,  382,  382,  382,  410,  410,  382,  382,
      382,  411,  411,  382,  382,  382,  412,  412,  382,  382,
      382,  413,  413,  382,  382,  382,  414,  414,  382,  382,
      382,  415,  415,  382,  382,  382,  416,  382,  382,  382,
      417,  382,  382,  382,  418,  382,  382,  382,  419,  382,
      382,  382,  420,  382,  382,  382,  421,  382,  382,  382,

      422,  382,  382,  382,  423,  382,  382,  382,  424,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,    0,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382
    } ;

static const flex_int16_t yy_nxt[1041] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,    4,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   30,
       31,   32,   29,   29,   33,   34,   35,   36,   37,   38,
       29,   39,   29,   40,   41,   29,   29,   29,   42,   43,
       44,   45,   46,   47,   29,   29,   48,   49,   50,   51,
       52,   52,   52,   52,   52,   52,   52,   52,   56,   52,
       58,  216,   52,   52,   61,   52,   52,   52,   52,   62,
       52,   52,   53,   59,   59,   59,   68,   69,   70,   63,
       60,   64,   64,   65,   63,   52,   64,   64,   65,   52,

       52,   55,   66,   71,   72,   83,   52,   52,   67,   52,
       88,   81,   52,   67,   63,   84,   65,   65,   65,   93,
       52,   74,   82,   75,   52,   52,   91,   76,   66,   92,
      382,   52,  210,   98,   77,   79,  103,  103,  103,   63,
       78,   65,   65,   65,   80,  203,   86,  382,   90,  194,
       98,   85,   89,   87,   63,  101,  104,  104,  105,   63,
      130,  105,  105,  105,   94,  131,  131,  131,  180,   95,
       96,  160,   63,   67,  132,  132,  133,  157,  157,  157,
       63,   97,  133,  133,  133,   63,  134,  158,  158,  159,
       63,   67,  159,  159,  159,  177,  177,  177,   63,  106,

      178,  178,  179,   63,   67,  179,  179,  179,  191,  191,
      191,   63,  273,  192,  192,  193,   63,   67,  193,  193,
      193,  200,  200,  200,   63,  268,  201,  201,  202,   63,
       67,  202,  202,  202,  207,  207,  207,   63,  263,  208,
      208,  209,   63,   67,  209,  209,  209,  213,  213,  213,
       63,  258,  214,  214,  215,   63,   67,  215,  215,  215,
      219,  219,  219,   63,  253,  220,  220,  221,   63,   67,
      221,  221,  221,  224,  224,  224,   63,  248,  225,  225,
      226,   63,   67,  226,  226,  226,  229,  229,  229,   63,
      243,  230,  230,  231,   63,   67,  231,  231,  231,  234,

      234,  234,   63,  238,  235,  235,  236,   63,   67,  236,
      236,  236,  239,  239,  239,   63,  233,  240,  240,  241,
       63,   67,  241,  241,  241,  244,  244,  244,   63,  228,
      245,  245,  246,   63,   67,  246,  246,  246,  249,  249,
      249,   63,  223,  250,  250,  251,   63,   67,  251,  251,
      251,  254,  254,  254,   63,  218,  255,  255,  256,   63,
       67,  256,  256,  256,  259,  259,  259,   63,  212,  260,
      260,  261,   63,   67,  261,  261,  261,  264,  264,  264,
       63,  206,  265,  265,  266,   63,   67,  266,  266,  266,
      269,  269,  269,   63,  205,  270,  270,  271,   63,   67,

      271,  271,  271,  274,  274,  274,   63,  199,  275,  275,
      276,   63,   67,  276,  276,  276,  278,  278,  278,   63,
      198,  279,  279,  280,   63,   67,  280,  280,  280,  282,
      282,  282,   63,  197,  283,  283,  284,   63,   67,  284,
      284,  284,  286,  286,  286,   63,  196,  287,  287,  288,
       63,   67,  288,  288,  288,  290,  290,  290,   63,  190,
      291,  291,  292,   63,   67,  292,  292,  292,  294,  294,
      294,   63,  189,  295,  295,  296,   63,   67,  296,  296,
      296,  298,  298,  298,   63,  188,  299,  299,  300,   63,
       67,  300,  300,  300,  302,  302,  302,   63,  187,  303,

      303,  304,   63,   67,  304,  304,  304,  306,  306,  306,
       63,  186,  307,  307,  308,   63,   67,  308,  308,  308,
      310,  310,  310,   63,  185,  311,  311,  312,   63,   67,
      312,  312,  312,  314,  314,  314,   63,  184,  315,  315,
      316,   63,   67,  316,  316,  316,  317,  317,  317,   63,
      183,  318,  318,  319,   63,   67,  319,  319,  319,  320,
      320,  320,  321,  321,  322,  322,  322,  322,   67,  323,
      323,  324,  324,  324,  324,  325,  325,  326,  182,   67,
      326,  326,  326,  327,  327,  328,   67,  328,  328,  328,
      176,  175,   67,  329,  329,  330,  330,  330,  330,  174,

       67,  331,  331,  332,  332,  332,  332,  333,  333,  334,
       67,  334,  334,  334,  335,  335,  336,  173,   67,  336,
      336,  336,  172,  171,   67,  337,  337,  338,  338,  338,
      338,   67,  339,  339,  340,  340,  340,  340,  341,  341,
      342,  170,   67,  342,  342,  342,  343,  343,  344,   67,
      344,  344,  344,  169,  168,   67,  345,  345,  346,  346,
      346,  346,  167,   67,  347,  347,  348,  348,  348,  348,
      349,  349,  350,   67,  350,  350,  350,  351,  351,  352,
      166,   67,  352,  352,  352,  165,  164,   67,  353,  353,
      354,  354,  354,  354,   67,  355,  355,  356,  356,  356,

      356,  357,  357,  358,  163,   67,  358,  358,  358,  359,
      359,  360,   67,  360,  360,  360,  162,  101,   67,  361,
      361,  362,  362,  362,  362,  156,   67,  363,  363,  364,
      364,  364,  364,  365,  365,  366,   67,  366,  366,  366,
      367,  367,  368,  155,   67,  368,  368,  368,  154,  153,
       67,  369,  369,  370,  370,  370,  370,   67,  371,  371,
      372,  372,  372,  372,  373,  373,  374,  152,   67,  374,
      374,  374,  375,  375,  376,   67,  376,  376,  376,  151,
      150,   67,  377,  377,  378,  378,  378,  378,  149,   67,
      379,  379,  317,  317,  317,  317,  380,  380,  320,   67,

      381,  381,  381,  381,  148,  147,  146,   67,  145,  144,
      143,  142,  141,   67,  140,  139,  138,   67,  137,   67,
       54,   54,   54,   54,   54,   54,   57,   57,   57,   57,
       73,  136,   73,   73,   73,  100,  100,  100,  100,  100,
      100,  102,  101,  102,  102,  102,  102,  107,  107,  107,
      135,  135,  135,  161,  161,  161,  181,  181,  181,  195,
      195,  195,  204,  204,  204,  211,  211,  211,  217,  217,
      217,  222,  222,  222,  227,  227,  227,  232,  232,  232,
      237,  237,  237,  242,  242,  242,  247,  247,  247,  252,
      252,  252,  257,  257,  257,  262,  262,  262,  267,  267,

      267,  272,  272,  272,  277,  277,  277,  281,  281,  281,
      285,  285,  285,  289,  289,  289,  293,  293,  293,  297,
      297,  297,  301,  301,  301,  305,  305,  305,  309,  309,
      309,  313,  313,  313,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  101,   58,   99,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  382,    3,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382
    } ;

static const flex_int16_t yy_chk[1041] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        7,    9,   11,   12,   19,   25,   26,   18,   11,   36,
       12,  402,   44,   37,   19,   20,   33,   43,   40,   19,
       21,   27,    7,   18,   18,   18,   25,   25,   26,   20,
       18,   20,   20,   20,   21,   34,   21,   21,   21,   35,

       22,    9,   20,   27,   27,   37,   38,   41,   20,   39,
       40,   36,   42,   21,   22,   37,   22,   22,   22,   44,
       45,   33,   36,   33,   46,   49,   43,   34,   20,   43,
       54,   47,  400,   54,   34,   35,   63,   63,   63,   59,
       34,   59,   59,   59,   35,  398,   39,   98,   42,  396,
       98,   38,   41,   39,   64,  101,   64,   64,   64,   65,
      101,   65,   65,   65,   45,  103,  103,  103,  394,   46,
       47,  392,  104,   64,  104,  104,  104,  131,  131,  131,
      105,   49,  105,  105,  105,  132,  390,  132,  132,  132,
      133,  104,  133,  133,  133,  157,  157,  157,  158,  388,

      158,  158,  158,  159,  132,  159,  159,  159,  177,  177,
      177,  178,  268,  178,  178,  178,  179,  158,  179,  179,
      179,  191,  191,  191,  192,  263,  192,  192,  192,  193,
      178,  193,  193,  193,  200,  200,  200,  201,  258,  201,
      201,  201,  202,  192,  202,  202,  202,  207,  207,  207,
      208,  253,  208,  208,  208,  209,  201,  209,  209,  209,
      213,  213,  213,  214,  248,  214,  214,  214,  215,  208,
      215,  215,  215,  219,  219,  219,  220,  243,  220,  220,
      220,  221,  214,  221,  221,  221,  224,  224,  224,  225,
      238,  225,  225,  225,  226,  220,  226,  226,  226,  229,

      229,  229,  230,  233,  230,  230,  230,  231,  225,  231,
      231,  231,  234,  234,  234,  235,  228,  235,  235,  235,
      236,  230,  236,  236,  236,  239,  239,  239,  240,  223,
      240,  240,  240,  241,  235,  241,  241,  241,  244,  244,
      244,  245,  218,  245,  245,  245,  246,  240,  246,  246,
      246,  249,  249,  249,  250,  212,  250,  250,  250,  251,
      245,  251,  251,  251,  254,  254,  254,  255,  206,  255,
      255,  255,  256,  250,  256,  256,  256,  259,  259,  259,
      260,  198,  260,  260,  260,  261,  255,  261,  261,  261,
      264,  264,  264,  265,  196,  265,  265,  265,  266,  260,

      266,  266,  266,  269,  269,  269,  270,  189,  270,  270,
      270,  271,  265,  271,  271,  271,  274,  274,  274,  275,
      185,  275,  275,  275,  276,  270,  276,  276,  276,  278,
      278,  278,  279,  183,  279,  279,  279,  280,  275,  280,
      280,  280,  282,  282,  282,  283,  182,  283,  283,  283,
      284,  279,  284,  284,  284,  286,  286,  286,  287,  176,
      287,  287,  287,  288,  283,  288,  288,  288,  290,  290,
      290,  291,  174,  291,  291,  291,  292,  287,  292,  292,
      292,  294,  294,  294,  295,  173,  295,  295,  295,  296,
      291,  296,  296,  296,  298,  298,  298,  299,  171,  299,

      299,  299,  300,  295,  300,  300,  300,  302,  302,  302,
      303,  170,  303,  303,  303,  304,  299,  304,  304,  304,
      306,  306,  306,  307,  168,  307,  307,  307,  308,  303,
      308,  308,  308,  310,  310,  310,  311,  165,  311,  311,
      311,  312,  307,  312,  312,  312,  314,  314,  314,  315,
      164,  315,  315,  315,  316,  311,  316,  316,  316,  317,
      317,  317,  318,  318,  318,  319,  319,  319,  315,  321,
      321,  321,  322,  322,  322,  323,  323,  323,  163,  318,
      324,  324,  324,  325,  325,  325,  321,  326,  326,  326,
      156,  155,  323,  327,  327,  327,  328,  328,  328,  153,

      325,  329,  329,  329,  330,  330,  330,  331,  331,  331,
      327,  332,  332,  332,  333,  333,  333,  151,  329,  334,
      334,  334,  150,  149,  331,  335,  335,  335,  336,  336,
      336,  333,  337,  337,  337,  338,  338,  338,  339,  339,
      339,  148,  335,  340,  340,  340,  341,  341,  341,  337,
      342,  342,  342,  147,  146,  339,  343,  343,  343,  344,
      344,  344,  145,  341,  345,  345,  345,  346,  346,  346,
      347,  347,  347,  343,  348,  348,  348,  349,  349,  349,
      144,  345,  350,  350,  350,  143,  141,  347,  351,  351,
      351,  352,  352,  352,  349,  353,  353,  353,  354,  354,

      354,  355,  355,  355,  140,  351,  356,  356,  356,  357,
      357,  357,  353,  358,  358,  358,  137,  130,  355,  359,
      359,  359,  360,  360,  360,  129,  357,  361,  361,  361,
      362,  362,  362,  363,  363,  363,  359,  364,  364,  364,
      365,  365,  365,  128,  361,  366,  366,  366,  127,  126,
      363,  367,  367,  367,  368,  368,  368,  365,  369,  369,
      369,  370,  370,  370,  371,  371,  371,  125,  367,  372,
      372,  372,  373,  373,  373,  369,  374,  374,  374,  124,
      123,  371,  375,  375,  375,  376,  376,  376,  122,  373,
      377,  377,  377,  378,  378,  378,  379,  379,  379,  375,

      380,  380,  381,  381,  121,  120,  118,  377,  117,  116,
      115,  114,  113,  379,  112,  111,  110,  380,  109,  381,
      383,  383,  383,  383,  383,  383,  384,  384,  384,  384,
      385,  108,  385,  385,  385,  386,  386,  386,  386,  386,
      386,  387,  100,  387,  387,  387,  387,  389,  389,  389,
      391,  391,  391,  393,  393,  393,  395,  395,  395,  397,
      397,  397,  399,  399,  399,  401,  401,  401,  403,  403,
      403,  404,  404,  404,  405,  405,  405,  406,  406,  406,
      407,  407,  407,  408,  408,  408,  409,  409,  409,  410,
      410,  410,  411,  411,  411,  412,  412,  412,  413,  413,

      413,  414,  414,  414,  415,  415,  415,  416,  416,  416,
      417,  417,  417,  418,  418,  418,  419,  419,  419,  420,
      420,  420,  421,  421,  421,  422,  422,  422,  423,  423,
      423,  424,  424,  424,   99,   96,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   85,   84,   83,   82,   81,
       79,   78,   77,   76,   75,   74,   61,   57,   55,   51,
       50,   48,   32,   31,   30,   29,   28,   24,   23,   17,
       16,   15,   14,   13,   10,    8,    6,    4,    3,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[70] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiladores.lex"
/*
 * Compiladores
 * 
 */
#line 7 "compiladores.lex"
#include "lex.yy.h"
int col = 1;


#line 841 "lex.yy.c"
#line 842 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "compiladores.lex"

#line 1061 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 383 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 980 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "compiladores.lex"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 36 "compiladores.lex"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "compiladores.lex"
col++;
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 38 "compiladores.lex"
col = 1;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "compiladores.lex"
col += yyleng; return DO;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "compiladores.lex"
col += yyleng; return KW_MODULE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "compiladores.lex"
col += yyleng; return KW_WHILE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "compiladores.lex"
col += yyleng; return KW_EXTERN;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "compiladores.lex"
col += yyleng; return KW_BREAK;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "compiladores.lex"
col += yyleng; return KW_CONTINUE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "compiladores.lex"
col += yyleng; return KW_IF;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "compiladores.lex"
col += yyleng; return KW_ELSE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "compiladores.lex"
col += yyleng; return KW_FALSE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "compiladores.lex"
col += yyleng; return KW_TRUE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "compiladores.lex"
col += yyleng; return KW_SWITCH;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "compiladores.lex"
col += yyleng; return KW_CASE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "compiladores.lex"
col += yyleng; return KW_DEFAULT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "compiladores.lex"
col += yyleng; return KW_GOTO;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "compiladores.lex"
col += yyleng; return KW_LABEL;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "compiladores.lex"
col += yyleng; return KW_INT;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "compiladores.lex"
col += yyleng; return KW_BOOL;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "compiladores.lex"
col += yyleng; return KW_FLOAT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "compiladores.lex"
col += yyleng; return KW_CHAR;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "compiladores.lex"
col += yyleng; return KW_UNTYPED;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "compiladores.lex"
col += yyleng; return KW_VOID;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "compiladores.lex"
col += yyleng; return KW_RETURN;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "compiladores.lex"
col += yyleng; return KW_START;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "compiladores.lex"
col += yyleng; return ARROW;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "compiladores.lex"
col += yyleng; return LBRACE;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "compiladores.lex"
col += yyleng; return RBRACE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "compiladores.lex"
col += yyleng; return LPAREN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "compiladores.lex"
col += yyleng; return RPAREN;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "compiladores.lex"
col += yyleng; return LBRACKET;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "compiladores.lex"
col += yyleng; return RBRACKET;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "compiladores.lex"
col += yyleng; return COMMA;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "compiladores.lex"
col += yyleng; return OP_ADD;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "compiladores.lex"
col += yyleng; return OP_SUBTRACT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "compiladores.lex"
col += yyleng; return OP_BITWISE_COMPLEMENT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "compiladores.lex"
col += yyleng; return OP_MULTIPLY;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "compiladores.lex"
col += yyleng; return OP_DIVIDE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "compiladores.lex"
col += yyleng; return OP_MODULUS;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "compiladores.lex"
col += yyleng; return OP_LESS;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "compiladores.lex"
col += yyleng; return OP_LESSEQUAL;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "compiladores.lex"
col += yyleng; return OP_GREATER;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "compiladores.lex"
col += yyleng; return OP_GREATEREQUAL;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "compiladores.lex"
col += yyleng; return OP_EQUAL;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "compiladores.lex"
col += yyleng; return OP_NOTEQUAL;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "compiladores.lex"
col += yyleng; return OP_LOGICAL_OR;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "compiladores.lex"
col += yyleng; return OP_NOT;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "compiladores.lex"
col += yyleng; return OP_BITWISE_RSHIFT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "compiladores.lex"
col += yyleng; return OP_BITWISE_LSHIFT;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "compiladores.lex"
col += yyleng; return OP_BITWISE_XOR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "compiladores.lex"
col += yyleng; return OP_LOGICAL_AND;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "compiladores.lex"
col += yyleng; return OP_BITWISE_AND;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "compiladores.lex"
col += yyleng; return SEMICOLON;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "compiladores.lex"
col += yyleng; return COLON;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "compiladores.lex"
col += yyleng; return OP_ASSIGN;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "compiladores.lex"
col += yyleng; return OP_BITWISE_OR;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "compiladores.lex"
col += yyleng; return OP_TERNARY_IF;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "compiladores.lex"
col += yyleng; return KW_IMPORT;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "compiladores.lex"
col += yyleng; return HEX;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "compiladores.lex"
col += yyleng; return BIN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "compiladores.lex"
col += yyleng; return INT;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "compiladores.lex"
col += yyleng; return FLOAT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "compiladores.lex"
col += yyleng; return CHAR;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "compiladores.lex"
col += yyleng; return STRING;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "compiladores.lex"
col += yyleng; return IDENTIFIER;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 102 "compiladores.lex"
col += yyleng; return ERROR;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "compiladores.lex"
ECHO;
	YY_BREAK
#line 1475 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 383 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 383 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 382);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 103 "compiladores.lex"

int yywrap(void) {
    return 1;
}
